### ISSUE TITLE
Real time object detection and recognition

### ISSUE THREAD

**Issue by DaraYo** [ftn-ai-lab/sc-2017-siit#13]
**Tim**
SW 85/2017 Aleksandar Đurić
SW 86/2017 Dara Jovanović
SW 90/2017 Milica Lazić

**Definicija problema**
Detektovanje 15 različitih vrsta objekata sa video snimka.

**Motivacija problema**
Prepoznavanje objekata određenog tipa.

**Skup podataka**
Podaci za obuku se koriste iz dataset-a
http://cocodataset.org/#download

**Metodologije**
Python
OpenCV
CNN
Za  izdvajanje objekta od pozadine slike koristimo ThensorFlow object detection.
Prvo prevodimo sliku u crno-belu, gde je objekat crne boje, a pozadina bela (ili obrnuto). Na osnovu centra mase, objekat možemo da izrežemo sa slike. Nakon toga imenujemo objekat.

**Metod evaluacije**
Validacija rešenja će se vršiti na osnovu test skupa sa video klipova.

**Comment by vdragan1993** [comment]
Identičan projekat je već prijavljen.
Ili promenite temu, ili odaberite predefinisane projekte.

**Comment by DaraYo** [comment]
Nadam se da se sećate da smo već nakon prvih vežbi pričali o ovoj temi, i da ste se složili da to radimo. Zaista nismo upućeni šta su druge kolege odabrale za temu. 
Već smo dosta proučavali ovu temu.

**Comment by vdragan1993** [comment]
Isto tako je naglašeno da se prilikom prijave projekta ne prijavljuju već prijavljene teme. Zato je prijava svih projekata javna.

Ili smislite neko proširenje na postojeći predlog (ako ste istraživali, to vam neće biti problem), ili smislite drugu ideju, ili odaberite predefinisane projekte.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by AlexSensei** [comment]
https://github.com/FoxGrayy/Real-time-object-detection-and-recognition
