### ISSUE TITLE
Slaganje puzle

### ISSUE THREAD

**Issue by lazarevicnevena** [ftn-ai-lab/sc-2017-siit#14]
Tim

Rados Acimovic, SW 18/2014
Nevena Lazarevic, SW 43/2014
Filip Jablanovic, SW 96/2016

Definicija problema

Slaganje puzle.

Motivacija problema

Prepoznati sve delove puzle i potom odrediti tacan raspored svih delova i tako sklopiti puzlu.

Skup podataka

Skup slika sa interneta koje cemo, zahvaljujuci programu koji cemo napraviti, praviti u delove puzle, a
koje cemo kasnije koristi za ucenje. 

Metodologija

Potrebno je iskoristiti algoritam za isecanje objekata, koji nam je od znacaja sa slike, u nasem slucaju to predstavlja puzlu (bez ostatka slike) koju kasnije koristimo za slaganje i odredjivanje njene pozicije. 
Zatim nam je potrebna neuronska mreza koja ce prepoznati slicnost dve slike, koju kasnije koristimo za prolazak kroz sliku i poredjenjenje delova slike sa puzlom. Tako odredjujemo koji deo puzle odgovara datoj lokaciji. 

Metod evaluacije

Mjeriće se tačnost (Accuracy) prepoznavanja.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by lazarevicnevena** [comment]
Hvala.

[Link](https://github.com/lazarevicnevena/puzzle-solving)

**Comment by lazarevicnevena** [comment]
Hvala.

[Git Repository](https://github.com/lazarevicnevena/puzzle-solving)
