### ISSUE TITLE
Evolutivni algoritam za crtanje slike na osnovu neuronske mreže

### ISSUE THREAD

**Issue by dtoma95** [ftn-ai-lab/sc-2017-siit#16]
Tim
----
Tomislav Dobrički SW21-2014
Ognjen Vlajić SW15-2014
GitHub: https://github.com/dtoma95/Soft_computing_picture_generation

Definicija problema
----
Ideja jeste da se napravi evolutivni algoritam koji može za bilo koju neuronsku mrežu (koja radi klasifikaciju slika) izgeneriše sliku za koja će "prevariti" datu neuronsku mrežu.

Metodologija
----
Za implementaciju evolutivnog algoritma će se koristiti programski jezik python zajedno sa nekim bibliotekama koji olakšavaju manipulaciju nad slikama (npr openCV). Jednu generaciju u algoritmu će predstavljati skup slika. Svaka slika će biti poslata u neuronsku mrežu a za fitness funkciju će se uzimati povratna vrednost iz mreže.
Za kompleksnije NM je možda potrebno da se za fitness funkciju uzimaju i vrednosti iz svakog neurona nekog sloja pojedinačno. U tom slučaju evolutivni algoritam ne mora da crta celu sliku odjednom, već će se odvojeno crtati slika za svaki neuron, s tim što će se gledati samo pikseli u slici za koje taj neuron pokazuje najveću pobuđenost. (https://github.com/yosinski/deep-visualization-toolbox). 

Evaluacija
----
Za evaulaciju će se uzimati nekoliko neuronskih mreža koji prepoznavaju određene objekte na slikama, zatim će evolutivni algoritam izgenerisati slike za svaki od njih. Te slike će se zatim poslati u neke neuronske mreže koje su u potpunosti odvojene od onih nad kojima se generisala slika, ali klasifikuju iste objekte. Na kraju će se gledati količina izgenerisanih slika koje su uspešno "prevarile" oba klasifikatora

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
