### ISSUE TITLE
Prepoznavanje sličnih lica

### ISSUE THREAD

**Issue by nevenaDj** [ftn-ai-lab/sc-2017-siit#17]
1.	Tim  
Nevena Đerić SW20-2014
Noemi Sabadoš SW2-2014

2.	Definicija problema 
Na osnovu prepoznatog lica sa učitane slike, traženje  lica iz seta podataka koja imaju najviše sličnosti sa njim.  

3.	Skup podataka 
https://data.vision.ee.ethz.ch/cvl/rrothe/imdb-wiki/

4.	Metodologija 
Koristimo Python jezik.
-	Detekcija lica – HOG (dlib)
-	Poziranje lica (68 tačka) – dlib
-	Transformacija slike tako da lice zauzima centralni deo slike - OpenFace
-	Kodiranje lica – tflearn (sa neuronskim mrežama)
-	Dobijanje ličnost – sklearn (sa SVM klasifikacijom)

5.	Metod evaluacije 

1)	Preko https://www.faceplusplus.com/face-comparing/#demo sajta
Uplodujemo nase fotografije (100 primer) i gledamo da li smo dobili slicnost (+-5%) 
2)	Ne koristimo ceo skup slika, nego samo nekoliko. Mi selektujemo slike tako da bude nekoliko grupa. Svaka grupa treba da ima 5-10 slika i njihova lica treba da budu slicna (npr. porodnične slike). Za svaku sliku, kao rezultat treba da dobijemo slike iz iste grupe.
3)	Poredimo dve različite slike lica iste osobe, treba da dobijemo sličnost min 80%.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by nevenaDj** [comment]
Hvala :)

[GitHub repozitorijum](https://github.com/nevenaDj/SC)
