### ISSUE TITLE
Pravljenje panorame od slika

### ISSUE THREAD

**Issue by vojinp** [ftn-ai-lab/sc-2017-siit#18]
**Autor**
- SW37-2014 Vojin Pešalj

**Definicija problema**
Spajanje više slika u panoramu, kako bi se zabeležio veći prizor koji ne može da stane u fotografiju standardnih dimenzija.

**Skup podataka**
http://www.cvl.isy.liu.se/en/research/datasets/passta/

**Metodologija**
- Pronalaženje ključnih tačaka 2 slike koje treba spojiti
- Pronalaženje povezanosti ključnih tačaka 2 slike korišćenjem knn algoritma
- Korišćenje homografije nad drugom slikom kako bi se njene ključne tačke poklopile sa onima sa prve
- Spajanje 2 slike u jednu

**Metod evaluacije**
Porediću dobijenu sliku sa rezultatom nekog od već postojećih programa za spajanje slika

**Git** https://github.com/vojinp/panorama

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
