### ISSUE TITLE
Klasifikacija i autentikacija otiska prsta

### ISSUE THREAD

**Issue by ivanazeljkovic** [ftn-ai-lab/sc-2017-siit#19]
**Student**
Ivana Zeljković (SW12-2014)

**Definicija problema**
Problem koji se rešava je autentikacija otiska prsta na osnovu postojećih otisaka u bazi podataka, tačnije provera korespodencije izmedju dva otiska na osnovu njihovih šablona i strukturnih elemenata. U procesu autentikacije najveći fokus je na klasifikaciji otisaka u jednu od mogućih 5 klasa (arch, tented arch, right loop, left loop, whorl - izvedene na osnovu strukture šablona otiska) što značajno redukuje veličinu prostora pretrage i povećava brzinu pronalaženja korespodentnog otiska u bazi podataka.

**Motivacija problema**
Rešenje pomenutog problema bi se praktično moglo primeniti u sistemima koji zahtevaju visok stepen bezbednosti, s obzirom da je otisak prsta jedinstveno obeležje svake osobe.

**Skup podataka**
Za obučavanje klasifikatora će se koristiti baza podataka: http://biometrics.idealtest.org/dbDetailForUser.do?id=7 koja obuhvata 20000 otisaka, pri čemu su u pitanju otisci 500 različitih osoba.
Za validaciju obučenosti klasifikatora će se koristiti baza podataka: https://www.nist.gov/srd/nist-special-database-4 koja obuhvata 2000 labeliranih otisaka.

**Metodologija**
Pretprocesiranje i priprema ulaznih podataka: binarizacija, detekcija ivica, segmentacija, filtriranje specijalizovanim filterima namenjenim za odredjivanje orijentacije u analizi tekstura (Gabor filter) itd.
Prepoznavanje konkretne klase upotrebom višeslojnog perceptrona.

**Metod evaluacije**
Klasifikacija: Mera preciznosti nad testnim skupom podataka za klasifikaciju.
Autentikacija: Mera preciznosti nad testnim skupom podataka za autentikaciju.

**GitHub repozitorijum**
https://github.com/ivanazeljkovic/Fingerprint_classification_authentication

**Asistent**
Ivan Perić @ivan7792

**Comment by ivan7792** [comment]
Tema odobrena. Srećan rad.
