### ISSUE TITLE
Detekcija istinitosti iskaza na osnovu facijalne ekspresije

### ISSUE THREAD

**Issue by saraperic13** [ftn-ai-lab/sc-2017-siit#20]
**Autor:**

- Sara Perić sw26/2014

**Definicija problema:**
Potrebno je detektovati istinitost iskaza osobe sa video snimka na osnovu njene/njegove facijalne ekspresije u trenutku odgovora. Parametri koji će se pratiti:

- Treptanje očiju
- Rumenilo
- Usne.

**Motivacija problema:**
U zavisnosti od uspeha realizacije, smatram da bi u kombinaciji sa poligrafom i nadogradnjom projekta (praćenjem dodatnih parametara) moglo dati dobre rezultate pri krivičnom gonjenju optuženih. Takođe, može poslužiti kao razonoda.

**Skup podataka:**
Ručno pravljeni skup od po desetak snimaka na kojima osobe govore istinu i neistinu.

**Metodologija:**
Implementacija će biti sprovedena korišćenjem dlib, OpenCV i  Python-a za pronalaženje i praćenje interesnih tačaka lica. Na osnovu prikupljenih podataka biće kreirane vektorske reprezentacije istih potom korišćene u KNN klasifikaciji ili će biti obučena neuronska mreža i naknadno sprovedeno utvrđivanje koji pristup je bolji.

**Metod evaluacije:**
Empirijski.

**Asistent:**
[Ivan Perić](https://github.com/ivan7792)

**Repozitorijum:**
https://github.com/saraperic13/LieDetector

**Comment by ivan7792** [comment]
Tema odobrena. Srećan rad.
