### ISSUE TITLE
Face Detection and Recognition on Video Streams

### ISSUE THREAD

**Issue by Ackos95** [ftn-ai-lab/sc-2017-siit#23]
**Autor**:
Acko Spasic, SW-24/2014

**Definicija problema**:
Na osnovu video zapisa potrebno je da se izdvoje ljudi (njihova lica) i da se na neki nacin identifikuju. Tema je prakticno integracija dva odvojena problema, izdvajanje lica sa slike (video zapisa) i identifikovanje lica (odnosno pronalazak slicnosti sa nekim licem iz baze - klasifikacija na osnovu trening seta).

**Motivacija problema**:
Ukoliko je resenje dovoljno dobro uradjeno i postoji dobra baza lica, samo resenje moze da se iskoristi u bezbedonosne svrhe (policija, snimci kradja i slicno). Ali isto tako moze da ima i manje znacajne primene, na primer prepoznavanje glumaca u seriji/filmu (radi lakseg pronalaska istih).

**Skup podataka**:
Za konkretan primer koristicemo rucno napravljen skup podataka (slike poznatih glumaca).

**Metodologija**:
Rešavanje problema se sastoji iz nekoliko koraka:
1) Pronalaženje lica na fotografiji - koristiću HOG
2) Određivanje ključnih tačaka na licu - koristiću "Face landmark estimation" algoritam da pronađem 68 specifičnih tačaka na licu(oči, nos, usta..). Ovo radim jer glava može da se nalazi u različitim pozama tj. pod različitim uglovima. Na ovaj način ću nezavisno od toga kako je glava okrenuta uvek moći da centriram oči i usta.
3) Prepoznavanje lica - koristiću konvolucionu neuronsku mrežu

**Metod evaluacije**:
Podaciće  biti podeljeni na trening, test i validacioni skup. Kao metod evaluacije koristiću Accuracy tj. tačnost prepoznavanih lica.

**Asistent**:
@vdragan1993 Dragan Vidaković

**Comment by vdragan1993** [comment]
Dati opis metodologije nije dovoljno precizan, proširite ga.
Empirijska validacija za ovaj tip problema nije reprezentativna. Definišite drugi metod evaluacije.

**Comment by Ackos95** [comment]
@vdragan1993 

Metodologija i Metod evaluacije su prosireni, nadam se da je sada sve u redu.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu.
Srećan rad.

**Comment by Ackos95** [comment]
Evo i [repozitorijuma](https://github.com/Ackos95/FaceRecongition), sa malim zakasnjenjem
