### ISSUE TITLE
Prepoznavanje tipa sporta

### ISSUE THREAD

**Issue by nEMANJAhub** [ftn-ai-lab/sc-2017-siit#25]
**Tim**
Nemanja Ðuricic, SW 91/2017
Stefan Kikanović SW 90/2016
Vladislav Milivojević SW 91/2016

**Definicija problema**
Prepoznavanje tipa sporta na osnovu pokreta sportiste. 
Mreža će biti obučena da prepoznaje 10 vrsta olimpijskih sportova. Na osnovu specifičnog pokreta sportiste odredićemo tip sporta.

**Motivacija problema**
Ovo rešenje se može integrisati u bilo koju aplikaciju koja ima potrebu za tim.

**Skup podataka**
http://sam.johnson.io/research/lsp.html

**Metodologija**
Upotrebom tresholdinga izdvojićemo sportistu od pozadine slike, nakon cega ćemo neuronsku mrežu obučiti za prepoznavanje pokreta sportiste i na osnovu toga odrediti tip sporta.
Python, OpenCV

**Metod evaluacije**
Kao metod evaluacije imaćemo trening, validacioni i test skup, tako što ćemo na trening skupu obučiti a na validacionom skupu meriti odstupanja i popravljati da bi dobili bolje rezultate.

**Repozitorijum:**
[Link](https://github.com/nEMANJAhub/SoftComputing)

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
