### ISSUE TITLE
Prepoznavanje ptica na slici i određivanje njene vrste

### ISSUE THREAD

**Issue by davidvuletas** [ftn-ai-lab/sc-2017-siit#27]
# Autori

- Jelena Ilić SW42/2014

- David Vuletaš SW54/2014

# Repozitorijum
https://github.com/davidvuletas/recognition-of-birds

# Definicija problema
Potrebno je detektovati pticu na slici i odrediti kojoj vrsti pronađena ptica pripada.

# Motivacija problema
Bilo bi korisno imati mogućnost da prilikom posmatranja uslikamo pticu i odredimo kojoj vrsti pripada, kako radi naše lične informisanosti, tako i radi zaštite ugroženih vrsta.

# Skup podataka
Koristićemo već napravljen dataset koji sadrži oko 12000 slika sa po 200 vrsta i nalazi se na linku: 
http://www.vision.caltech.edu/visipedia/CUB-200-2011.html

# Metodologija
Za ovaj problem koji ćemo rešavati potrebno za početak izdvojiti samu pticu sa slike. To ćemo raditi korišćenjem threshold-a (izbacivanjem pozadine koja nam nije od važnosti). Samo prepoznavanje vrste ptice rešićemo korišćenjem neuronske mreže.

# Metod evaluacije 
Od već postojećeg dataset-a će biti odvojeni podaci koji će biti korišteni za validaciju. Planiramo da 70% dataset-a koristimo za obučavanje neuronske mreže, a ostatak odnosno 30% za testiranje i validaciju rezultata.

# Asistent
Stefan Anđelić @StefanAndjelic

**Comment by StefanAndjelic** [comment]
Odobrena tema, uz napomenu da se u metodologiju i pristup dodaju dogovoreni koraci.
