### ISSUE TITLE
Landmark recognition

### ISSUE THREAD

**Issue by marija-kovacevic** [ftn-ai-lab/sc-2017-siit#28]
# Tim
Marija Kovačević   SW22/2014
Drago Stevanović SW45/2014

# Definicija problema
Prepoznavanje znamenitosti koja je prikazana na fotografiji.

# Motivacija
Milioni turista dnevno obilaze svetske metropole, te je ideja za ovaj projekat nastala sa ciljem da im se olakša upoznavanje grada i njegovih bitnih znamenitosti. Za prosleđenu fotografiju, sistem će biti u stanju da izdvoji i prepozna znamenitost i da korisniku prosledi informaciju o kojoj znamenitosti se radi.

# Skup podataka
Skup podataka će činiti fotografije različitih znamenitosti, koje ćemo sami prikupiti pomoću Google Images i Street View (Google Maps).

# Metodologija
Na pripremljene fotografije, iz skupa podataka, primenićemo HOG transformaciju, uz pomoć koje će se izdvojiti deskriptor, koji će biti korišćen kao ulaz u klasifikator (neuronska mreža, SVM). Izlaz klasifikatora je naziv znamenitosti. 

# Metod evaluacije
Podaci će biti podeljeni u:

- trening,
- test i
- validacioni skup podataka.

Na fotografije iz test skupa će se primeniti HOG transformacija, nakon čega će se deskriptor dovoditi na ulaz klasifikatora i vršiti konačna predikcija znamenitosti i upoređivanje rezultata.

[Github repozitorijum](https://github.com/marija-kovacevic/Landmark-Recognition)

**Comment by vdragan1993** [comment]
Tema odobrena.
Srećan rad.
