### ISSUE TITLE
Prepoznavanje Parkinsonove bolesti i procena UPDRS-a kod obolelih pacijenata

### ISSUE THREAD

**Issue by andrejai** [ftn-ai-lab/sc-2017-siit#29]
**Asistent**: @vdragan1993

**Članovi tima**:
Andreja Isaković, SW 3/2014
Milica Mlađenović, SW 23/2014

**Definicija problema**:
Projekat se bavi prepoznavanjem Parkinsonove bolesti i određivanjem UPDRS-a kod obolelih pacijenata.

**Algoritmi**:

Neuronska mreža za prepoznavanje postojanja Parkinsonove bolesti
Neuronska mreža za procenjivanje motor i total UPDRS-a kod obolelih pacijenata

**Skup podataka**:

Prvi data set  https://archive.ics.uci.edu/ml/datasets/Parkinson+Speech+Dataset+with++Multiple+Types+of+Sound+Recordings#  sadrži numeričke podatke snimka govora pacijenata i koristićemo ga za prepoznavanje postojanja Parkinsonove bolesti.
Drugi data set https://archive.ics.uci.edu/ml/datasets/parkinsons+telemonitoring sadrži numeričke podatke snimka govora obolelih pacijenata i cilj je prepoznati motor i total UPDRS Parkinsonove bolesti.
Treći data set https://archive.ics.uci.edu/ml/datasets/Parkinson+Disease+Spiral+Drawings+Using+Digitized+Graphics+Tablet# ćemo iskoristiti za prepoznavanje postojanja Parkinsonove bolesti iz numeričkih podataka o slikama spirala. Pacijenti su crtali spirale i koordinate tih spirala su date u numeričkom obliku.

**Evaluacija**:

Kao metrika za poređenje koristiće se procenat tačnog određivanja pojave Parkinsona i procenat tačnog određivanja UPDRS-a gde će se tolerisati greške do 0,5 razlike. Data setovi će biti podeljeni na tri dela, najveći deo će biti podaci za treniranje neuronske mreže(oko 70%), podaci za validaciju(oko 10%) i test podaci(oko 20%).

Repozitorijum: https://github.com/andrejai/Parkinson-recognition

**Comment by vdragan1993** [comment]
Tema odobrena.
Srećan rad.
