### ISSUE TITLE
Klasifikacija instagram slika

### ISSUE THREAD

**Issue by nikolinaradicic** [ftn-ai-lab/sc-2017-siit#32]
## Tim
Nikolina Radičić sw27/2014
Uroš Jovanović sw89/2016

## Definicija problema
Za određenu kategoriju potrebno je identifikovati instagram slike na kojima se nalazi objekat te kategorije.

## Motivacija
Pretraga instagrama sa #kategorija ne vraća sigurno slike na kojima se nalazi objekat koji pripada toj kategoriji. Rješenje se može koristiti u cilju pronalaženja korisnika koji postavljaju fotografije određenog tipa, što se dalje može koristiti za pronalaženje korisnika koji bi mogao da reklamira neki proizvod ili za sistem za preporuku.

## Skup podataka
Skup podataka će biti prikupljen sa [http://image-net.org/](url) i sa instagrama.
Sadržaće slike koje pripadaju 10 kategorija (npr. bicikl, pas, mačka...) koje planiramo da prepoznajemo.
Takođe će sadržati slike koje ne pripadaju ovim kategorijama - one će sve spadati u jednu negativnu kategoriju.

## Metodologija
Za implementaciju će se koristiti python i biblioteka TensorFlow.
Klasifikacija slika će se raditi pomoću konvolucione neuronske mreže.

## Evaluacija
Podaci će biti podijeljeni na tri skupa - trening, validacioni i test.
Test skup će sadržati samo slike sa instagrama.
Za evaluaciju će se koristiti procenat tačnosti.

Repozitorijum [https://github.com/nikolinaradicic/SC_Projekat](https://github.com/nikolinaradicic/SC_Projekat)

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
