### ISSUE TITLE
Evolutivni algoritam za simulaciju učenja hodanja

### ISSUE THREAD

**Issue by brzaknemanja** [ftn-ai-lab/sc-2017-siit#34]
**TIM:**
Nemanja Brzak SW28-2014

**DEFINICIJA PROBLEMA:**
Ideja je da se napravi simulacija bipedalnog bića koje pomoću evolutivnog algoritma uči da hoda i održava ravnotežu. 
Primer: https://user-images.githubusercontent.com/20777345/34269658-8db1fa20-e685-11e7-8ed6-8a1fe9aa07a2.gif

**METODOLOGIJA:**
Za simulaciju bića bi se koristio Unity Game Engine i njegov 2D Physics Engine, a za ućenje hodanja bi se koristio evolutivni algoritam.

**EVALUACIJA:**
Za evaluaciju će se uzimati primeri jedinki koje su prešle najduži put hodajući.

**Asistent**

@vdragan1993 Dragan Vidaković

[Git Repository](https://github.com/freezurmom/Soft_computing_unity)

**Comment by vdragan1993** [comment]
Tema odobrena.
Srećan rad.
