### ISSUE TITLE
Sistem za davanje preporuka u muzici

### ISSUE THREAD

**Issue by nikolalosic** [ftn-ai-lab/sc-2017-siit#37]
**Tim**

Natalija Bogdanović, SW-36/2014
Dragan Vujanović, SW-11/2014
Nikola Lošić, SW-32/2014

**Definicija problema**

Preporuka muzičkog sadržaja korisnicima.

**Skup podataka**

U projektu će se koristiti gotovi skupovi podataka:

1) Million Song dataset: http://labrosa.ee.columbia.edu/millionsong/
2) Last.fm dataset: http://ocelma.net/MusicRecommendationDataset/index.html

**Metodologija**

Biće primenjen hibridni pristup. Koristiće se dva sistema za filtriranje:
1) Sistem za preporuku na osnovu saradnji (Collaborative filtering)
2) Sistem za preporuku na osnovu sadržaja (Content-based filtering)

**Metod evaluacije**

Evaluacija tačnosti preporuke  ispitivaće se korišćenjem sledećih metrika:

1) MAP (Mean Average Precision)
2) NDCG (Normalized Discounted Cumulative Gain)

**Asistent**

@vdragan1993 Dragan Vidaković

[Git Repository](https://github.com/nikolalosic/music-recommendation)

**Comment by vdragan1993** [comment]
Tema odobrena.
Srećan rad.
