### ISSUE TITLE
Detekcija i rešavanje magičnog kvadrata

### ISSUE THREAD

**Issue by vanjazoric** [ftn-ai-lab/sc-2017-siit#38]
## Tim
SW48/2014 Novak Marin
SW50/2014 Vanja Zorić
SW60/2014 Dušan Dudarin

## Definicija problema
Rešavanje magičnog kvadrata na osnovu učitane fotografije. Magični kvadrat predstavlja tablicu dimenzije NxN . Kada se popuni brojevima, njihov zbir treba biti isti i vertikalno, i horizontalno, i dijagonalno. Učitani kvadrat može biti proizvoljne dimenzije i proizvoljnog zbira. Takođe, inicijalno kvadrat je proizvoljno popunjen - može biti potpuno prazan ili već sadržati neke cifre.

## Motivacija problema
Program bi trebao da pomogne prilikom rešavanja magičnog kvadrata.

## Skup podataka
Za skup podataka koristiće se MNIST baza ručno pisanih cifara, kao i razne fotografije magičnog kvadrata (iz novina i sa računara), sa različitim osvetljenjem, jasnoćom i uglom slikanja.

## Metodologija

1. Priprema date slike: skaliranje i binarizacija
2. Detekcija grid-a i izdvajanje pronađenog prostora za dalju analizu
3. Detekcija brojeva isključivo unutar prostora na kojem se nalazi grid, pomoću neuronske mreže obučene na osnovu datog skupa podataka sa brojevima
4. Unos pronađenih brojeva u matricu koja ima dimenzije grid-a
5. Ukoliko su neka kolona, red ili dijagonala popunjeni, program zaključuje šta je traženi zbir; u suprotnom, zahteva se unos traženog zbira od strane korisnika
6. Provera da li se dati slučaj može rešiti
7. Rešavanje kvadrata putem nekoliko algoritama za koje budemo smatrali da su najadekvatniji (trenutna procena je da je genetski algoritam primeren za ovaj slučaj, ali možda pronađemo nešto korisnije)
8. Ukoliko je kvadrat moguće rešiti, korisniku se prikazuje popunjen kvadrat
9. Ukoliko kvadrat nije moguće rešiti, korisnik dobija obaveštenje da ne postoji rešenje datog kvadrata

## Metod evaluacije
Prilikom evaluacije rešenja koristiće se magični kvadrati za kojeg rešenje već postoji. Prvo će se proveravati da li su sve cifre pravilno prepoznate, a prazna polja na pravim mestima. Zatim detektuje sumu ako postoji. Na kraju, proverava se da li je rešenje ispravno.

- [Repozitorijum](https://github.com/vanjazoric/magic-square-solver)

- **Asistent**: Dragan Vidaković

**Comment by vdragan1993** [comment]
Tema odobrena.
Srećan rad.
