### ISSUE TITLE
Predefinisani projekat za ocenu 9 i 10

### ISSUE THREAD

**Issue by momir95** [ftn-ai-lab/sc-2017-siit#39]
Student : Momir Kostić SW41/2014
Asistent : Dragan Vidaković

Skup podataka nad kojim će biti urađen zadatak:
[Link](https://drive.google.com/drive/folders/0B1ZJXQY32LBUU3FiTS14a3NZd1U)

Video zapis poseduje dve pokretne linije koje je potrebno detektovati Hough
transformacijom.
Cifre prolaze iza pokretnih linija.
Cifre koje prođu ispod prve linije treba sabrati, a cifre koje pređu ispod druge linije treba
oduzeti od konačnog rezultata.
Potrebno postići tačnost prepoznavanja od bar 95%.

Repozitorijum: [link](https://github.com/momir95/Projekat-Soft)

**Comment by vdragan1993** [comment]
Repozitorijum projekta mora biti public GitHub repo.
