### ISSUE TITLE
"Samovozeci" automobil

### ISSUE THREAD

**Issue by kantagara** [ftn-ai-lab/sc-2017-siit#41]
## Tim
SW 94-2016 - Nikola Garabandić

## Definicija problema 
Uz pomoc Deep Q-Learninga automobil bi trebao da nauci samostalno da dodje od tacke A do tacke B (automobil nece dobiti neki predefinisan set pravila kako treba da se ponasa, vec ce morati sam da nauci sve). Ono sto otezava kretanje automobila jeste to da korisnik sam dodaje put i prepreke do cilja.

## Metodologija
Za implementaciju cu koristiti Kivy i PyTorch

## Evaluacija
Evaluacija je krajnje jednostavna. Ukoliko automobil dodje od tacke a do tacke b, neuronska mreza je dobro obucena 

## Asistent
@vdragan1993 Dragan Vidaković

Link do repozitorijuma:
https://github.com/kantagara/Soft-projekat

**Comment by vdragan1993** [comment]
Tema odobrena.
Srećan rad.
