### ISSUE TITLE
Ispitati da li je šut na koš regularan

### ISSUE THREAD

**Issue by dexa0704** [ftn-ai-lab/sc-2017-siit#42]
Članovi tima:

sw-33/2014 Dejan Zarić

**Definicija problema**

Radi se o košarkaškom pravilu. Ideja je proveriti da li je šut izveden regularno, odnosno, da li je lopta izbačena iz ruke pre nego što je istekao napad (vreme za napad na semaforu pokazuje nulu -0- ili se ivice table promene u crvenu boju).

**Motivacija problema**

Ovakav program bi pomogao rešavanju spornih situacija tokom utakmice. Često se dešava situacija da se ne zna tačno da li je šut regularan, pa bi ovo ubrzalo taj proces.

**Metodologije**

Projekat će biti implementiran u Python programskom jeziku. Za detekciju lopte sam planirao da koristim neki od algoritama za detekciju ivica kao što su Canny ili Hough Circle Transform. 
Za detekciju kraja napada preko semafora bih koristio neuronsku mrežu koja bi bila obučena MNIST dataset-om, dok bih u slučaju boje table takođe koristio neki od algoritama za detekciju konutra da bih detektovao tablu, a zatim proverio boju same table. 
Fotografije bih preprocesirao na način koji bi olakšao detekciju ruke igrača, a zatim bih poređenjem pozicije ruke i lopte utvrdio da li je lopta u kontaktu sa rukom.

**Skup podataka**

Data set bih pravio ručno u sportskoj hali. Napravio bih fotografije i sa njih vršio proveru. Verovatno bi sve fotografije bile pod istim uglom, da se jasno vide tabla i lopta.

**Evaluacija**

Rešenje će biti validirano empirijskim putem. Za testni skup podataka će se odrediti za svaki element skupa da li je regularan. Na osnovu broja regularno detektovanih šuteva, prikazaće se procentualna uspešnost projektnog rešenja. Koeficijent uspešnosti algoritma će se izraziti u intervalu [0, 100].

**Asistent:** @vdragan1993 (Dragan Vidaković)

Repozitorijum

[https://github.com/dexa0704/Buzzer-beater-or-not](url)

**Comment by vdragan1993** [comment]
Kako bi projekat bio još bolji, u skup podataka bi bilo poželjno ubaciti i fotografije iz drugih uglova (a da se jasno vide tabla i lopta).
Tema odobrena.
Ostavite link ka GitHub repozitorijumu.
Srećan rad.

**Comment by dexa0704** [comment]
U redu, biće i drugih uglova.
Hvala :)
Repozitorijum: [https://github.com/dexa0704/Buzzer-beater-or-not](url)
