### ISSUE TITLE
Detekcija lica i prepoznavanje osoba na slici/snimku

### ISSUE THREAD

**Issue by nole23** [ftn-ai-lab/sc-2017-siit#5]
# Članovi tima:
Novica Nikolić, SW93-2016

# Definicija problema:
Prepoznavanje i identifikovanje osoba na slici/snimku.

# Motivacija problema:
Danas sve vise modernih bezbednosnih sitema koriste neki vid identifikovanja osoba radi kontrole pristupa zaposlenim u kompaniji. Rešenje problema se može primeniti u bankovnim bezbednosnim sistemima kao jedan vidi kontrole zaposlenih. 
A detekcija osoba na slici je postao masovni problem za većinu društvenih mreža.
Na osnovu datih primjera primjene detekcije i identifikacije osoba, vidi se da sistem u današnjem vremenu nalazi primjenu na raznim problemima.

# Skup podatak:
Skup podataka za identifikovanje osoba ću ručno generisati na osnovu primjera. 

# Metodologija:
- Za realizaciju projekta koristiće se Python programski jezik i njegova OpenCV biblioteka. Pomocu  CascadeClassifier i skupa tacaka koje se koriste za detekciju lica [link](https://github.com/opencv/opencv/blob/master/data/haarcascades/haarcascade_frontalface_alt.xml) , izvršice se detekcija lica osobe. 

-  Na osnovu skupa podataka koji je predhodno generisan, obučiće se neuronska mreža pomću cv2.face.traing mehanizma kako bi dobili predikciju osoba na slici/snimku

 # Model evaluacije:
Kvalitet modela ce se odredjivati na osnovu tacnosti (Accuracy) klasterovanja slike iz testnog skupa podataka. 

# GitRepo
[Face recognition](https://github.com/nole23/face-recognition)

**Comment by vdragan1993** [comment]
Pošto se radi prepoznavanje i identifikovanje osoba (klasifikacija), zašto merite tačnost klasterovanja?

**Comment by nole23** [comment]
U istraživanju koje sam sproveo vezano za dati problem, nisam obratio dovoljno obratio pažnju. 
A u detaljnijem istraživanju za model evaluacije prepoznavanja i identifikovanja osoba koristio bi: precision, recall i f1-score.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by nole23** [comment]
Hvala.

[Link git-repository](https://github.com/nole23/face-recognition)
