### ISSUE TITLE
Detekcija šahovskih figura i njihovog položaja na tabli i simulacija partije

### ISSUE THREAD

**Issue by Gambit88** [ftn-ai-lab/sc-2017-siit#7]
**Tim**:  
SW87/2017 Đorđe Ilić
SW88/2017 Nikola Đurđević
SW89/2017 Mirjana Lakić

**Definicija problema**:
Pokušavamo da sa slike detektujemo šahovsku tablu, odredimo koje se figure nalaze na kojim položajima na tabli. Nakon detekcije, aplikacija nudi izbor nekoliko ai-a, koji su različito obučeni, koji bi  završili započetu partiju.

**Skup podataka**:
Planiramo da sami izvršimo kreiranje skupa podataka za detekciju figura, Svaka figura bi imala svoju labelu. Podaci bi bili sakupljeni slikanjem sa više različitih aparata, iz više različitih uglova.

**Metodologija**:
Na početku je potrebno da se pomoću detekcije ivica izvrši pronalaženje table, odnosno preciznije ćoška, na osnovu koga će se odrediti i ostala polja table, Prilikom detekcije figura možemo iskoristiti stablo odlučivanja/neuronske mreže. Figure bi poredili na osnovu ivica u cilju dobijanja tipa figure, a zatim na osnovu boje kako bi odredili kom timu pripadaju. Za obuku ai-a bi najverovatnije koristili evolucione algoritme, sa mogućnošću dodatnog ubacivanja neke jednostavnije pretrage. Prilikom obuke evolucionim algoritmom bi menjali evaluacionu formulu u cilju dobijanja različitih rezultata.

**Metod evaluacije**:
Kada je u pitanju evaluacija algoritma za detekciju figura koristićemo tačnost kao metod evaluacije.
Kada je u pitanju ai, koristimo identičnu klasičnu partiju šaha protiv identičnog protivnika, i nakon određenog broja poteza sumirati rezultate partije na osnovu preostalih figura i trenutnog statusa (da li je ai koji se testira pobedio partiju, izgubio ili je i dalje u toku).

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by Gambit88** [comment]
Link ka repozitorijumu:
https://github.com/Gambit88/chessDetectionAndSolver
