### ISSUE TITLE
Prepoznavanje bolesti na listu biljke 

### ISSUE THREAD

**Issue by kacacukurov** [ftn-ai-lab/sc-2017-siit#8]
**Tim:**

- Monika Erdeg, SW16/2014

- Katarina Čukurov, SW13/2014

**Definicija problema:**
Prepoznavanje bolesti pepelnica na listovima višnje i trešnje.

**Motivacija problema:**
Zbog učestale pojave bolesti na biljkama, a u isto vreme i sve veće rasprostranjenosti pametnih telefona, želimo da omogućimo poljoprivrednicima da na jednostavan način, putem naše aplikacije, otkriju od čega boluju biljke i na koji način da ih tretiraju. Za početak ćemo za ovaj projekat prepoznavati pepelnicu na listovima višnje i trešnje, ali je cilj da se to proširi kasnije na više bolesti i biljaka, kao i da postane mobilna aplikacija.

**Skup podataka:**

- link ka folderu sa bolesnim listovima: https://github.com/salathegroup/plantvillage_deeplearning_paper_dataset/tree/master/raw/color/Cherry_(including_sour)___Powdery_mildew

- link ka folderu sa zdravim listovima: https://github.com/salathegroup/plantvillage_deeplearning_paper_dataset/tree/master/raw/color/Cherry_(including_sour)___healthy

**Metodologija:**
Za izdvajanje lista sa pozadine, korisićemo treshold, a za prepoznavanje nepravilnosti na samom listu, K-means algoritam.

**Metod evaluacije:**
Kao metod evaluacije koristićemo konvolutivnu mrežu koja je obučena nad datim skupom podataka i ima tačnost 99,35%. Link ka rešenju: https://github.com/salathegroup/plantvillage_deeplearning_paper_analysis

**Link ka git repozitorijumu:**
https://gitlab.com/kaca.cukurov/Plant-Disease-Recognition

**Asistent:**
Ivan Perić @ivan7792

**Comment by ivan7792** [comment]
Tema odobrena. Srećan rad.
