### ISSUE TITLE
Detekcija i prepoznavanje saobraćajnih znakova

### ISSUE THREAD

**Issue by lukamaletin-zz** [ftn-ai-lab/sc-2017-siit#9]
## Tim
- Helena Zečević (sw6-2014)
- Luka Maletin (sw7-2014)
- Aleksandar Nikolić (sw25-2014)

## Definicija problema
Detekcija i prepoznavanje saobraćajnih znakova na slikama.

## Motivacija problema
Rešenje bi bilo praktično primenljivo u sistemu za asistenciju pri vožnji motornih vozila.
Ukoliko stignemo, ideja je da naše rešenje iskoristimo u tu svrhu u vidu Android aplikacije.

## Skup podataka
- [German Traffic Sign Detection Benchmark](http://benchmark.ini.rub.de/?section=gtsdb&subsection=dataset)
- [German Traffic Sign Recognition Benchmark](http://benchmark.ini.rub.de/?section=gtsrb&subsection=dataset)

## Metodologija
- Detekcija ivica (npr. Canny) praćena izdvajanjem kontura po geometrijskim osobinama (broj ivica, oblik, veličina), boji i drugo.
- Prepoznavanje konvolucionom neuronskom mrežom.

## Metod evaluacije
- Detekcija: [Recall, Precision](https://en.wikipedia.org/wiki/Precision_and_recall) nad celim skupom podataka za detekciju.
- Prepoznavanje: Mera preciznosti nad testnim skupom podataka za prepoznavanje.

## Asistent
[Ivan Perić](https://github.com/ivan7792)

## Repozitorijum
https://github.com/lukamaletin/traffic-signs-vision

**Comment by ivan7792** [comment]
Tema odobrena. Srećan rad.
